version: '3.8'

services:
  anna-music-bot:
    build: .
    container_name: anna-music-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
